### ISSUE TITLE
error running tests with newer versions

### ISSUE THREAD

**Issue by christopinka** [rkanter/MiniOozieExample#3]
with clone project and updating 

    <properties>
        <oozie.version>5.2.1</oozie.version>
        <hadoop.version>3.3.4</hadoop.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

getting
```

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ctopinka/.m2/repository/org/slf4j/slf4j-log4j12/1.6.6/slf4j-log4j12-1.6.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ctopinka/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

Setting testcase work dir[/Users/ctopinka/oss/MiniOozieExample/target/test-data/oozietests/com.github.rkanter.minioozieexample.TestRunWorkflow/testRunWorkflow/1c116b2a-d4a9-411f-9ee8-9bbee2d72c37]
2022-11-16 14:41:03,777 INFO  [main] minioozieexample.TestRunWorkflow (XLog.java:log(520)) - Oozie test resource file doesnt exist. [source.name={0}]
2022-11-16 14:41:03,782 INFO  [main] minioozieexample.TestRunWorkflow (XLog.java:log(520)) - Reading Oozie test resource from classpath. [testResourceName=hsqldb-oozie-site.xml;source.name=hsqldb-oozie-site.xml]
2022-11-16 14:41:03,827 WARN  [main] conf.Configuration (Configuration.java:<clinit>(796)) - DEPRECATED: hadoop-site.xml found in the classpath. Usage of hadoop-site.xml is deprecated. Instead use core-site.xml, mapred-site.xml and hdfs-site.xml to override properties of core-default.xml, mapred-default.xml and hdfs-default.xml respectively
2022-11-16 14:41:49,670 INFO  [main] Configuration.deprecation (Configuration.java:logDeprecation(1441)) - mapred.tasktracker.map.tasks.maximum is deprecated. Instead, use mapreduce.tasktracker.map.tasks.maximum
2022-11-16 14:41:49,763 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(60)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-11-16 14:41:50,389 INFO  [main] namenode.NameNode (NameNode.java:format(1251)) - Formatting using clusterid: testClusterID
2022-11-16 14:41:50,408 INFO  [main] namenode.FSEditLog (FSEditLog.java:newInstance(232)) - Edit logging is async:true
2022-11-16 14:41:50,437 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(814)) - KeyProvider: null
2022-11-16 14:41:50,438 INFO  [main] namenode.FSNamesystem (FSNamesystemLock.java:<init>(141)) - fsLock is fair: true
2022-11-16 14:41:50,439 INFO  [main] namenode.FSNamesystem (FSNamesystemLock.java:<init>(159)) - Detailed lock hold time metrics enabled: false
2022-11-16 14:41:50,464 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(847)) - fsOwner                = ctopinka (auth:SIMPLE)
2022-11-16 14:41:50,465 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(848)) - supergroup             = supergroup
2022-11-16 14:41:50,465 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(849)) - isPermissionEnabled    = true
2022-11-16 14:41:50,465 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(850)) - isStoragePolicyEnabled = true
2022-11-16 14:41:50,465 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:<init>(861)) - HA Enabled: false
2022-11-16 14:41:50,499 INFO  [main] common.Util (Util.java:isDiskStatsEnabled(395)) - dfs.datanode.fileio.profiling.sampling.percentage set to 0. Disabling file IO profiling
2022-11-16 14:41:50,503 INFO  [main] Configuration.deprecation (Configuration.java:logDeprecation(1441)) - hadoop.configured.node.mapping is deprecated. Instead, use net.topology.configured.node.mapping
2022-11-16 14:41:50,504 INFO  [main] blockmanagement.DatanodeManager (DatanodeManager.java:<init>(325)) - dfs.block.invalidate.limit: configured=1000, counted=60, effected=1000
2022-11-16 14:41:50,505 INFO  [main] blockmanagement.DatanodeManager (DatanodeManager.java:<init>(332)) - dfs.namenode.datanode.registration.ip-hostname-check=true
2022-11-16 14:41:50,508 INFO  [main] blockmanagement.BlockManager (InvalidateBlocks.java:printBlockDeletionTime(77)) - dfs.namenode.startup.delay.block.deletion.sec is set to 000:00:00:00.000
2022-11-16 14:41:50,509 INFO  [main] blockmanagement.BlockManager (InvalidateBlocks.java:printBlockDeletionTime(83)) - The block deletion will start around 2022 Nov 16 14:41:50
2022-11-16 14:41:50,510 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map BlocksMap
2022-11-16 14:41:50,510 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2022-11-16 14:41:50,512 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 2.0% max memory 1.8 GB = 36.4 MB
2022-11-16 14:41:50,512 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^22 = 4194304 entries
2022-11-16 14:41:50,524 INFO  [main] blockmanagement.BlockManager (BlockManager.java:createSPSManager(5412)) - Storage policy satisfier is disabled
2022-11-16 14:41:50,524 INFO  [main] blockmanagement.BlockManager (BlockManager.java:createBlockTokenSecretManager(633)) - dfs.block.access.token.enable = false
2022-11-16 14:41:50,532 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(160)) - dfs.namenode.safemode.threshold-pct = 0.999
2022-11-16 14:41:50,532 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(161)) - dfs.namenode.safemode.min.datanodes = 0
2022-11-16 14:41:50,532 INFO  [main] blockmanagement.BlockManagerSafeMode (BlockManagerSafeMode.java:<init>(163)) - dfs.namenode.safemode.extension = 0
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(619)) - defaultReplication         = 2
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(620)) - maxReplication             = 512
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(621)) - minReplication             = 1
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(622)) - maxReplicationStreams      = 2
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(623)) - redundancyRecheckInterval  = 3000ms
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(624)) - encryptDataTransfer        = false
2022-11-16 14:41:50,533 INFO  [main] blockmanagement.BlockManager (BlockManager.java:<init>(625)) - maxNumBlocksToLog          = 1000
2022-11-16 14:41:50,554 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - GLOBAL serial map: bits=29 maxEntries=536870911
2022-11-16 14:41:50,555 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - USER serial map: bits=24 maxEntries=16777215
2022-11-16 14:41:50,555 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - GROUP serial map: bits=24 maxEntries=16777215
2022-11-16 14:41:50,555 INFO  [main] namenode.FSDirectory (SerialNumberManager.java:<clinit>(51)) - XATTR serial map: bits=24 maxEntries=16777215
2022-11-16 14:41:50,570 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map INodeMap
2022-11-16 14:41:50,571 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2022-11-16 14:41:50,571 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 1.0% max memory 1.8 GB = 18.2 MB
2022-11-16 14:41:50,571 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^21 = 2097152 entries
2022-11-16 14:41:50,572 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(335)) - ACLs enabled? true
2022-11-16 14:41:50,572 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(339)) - POSIX ACL inheritance enabled? true
2022-11-16 14:41:50,572 INFO  [main] namenode.FSDirectory (FSDirectory.java:<init>(343)) - XAttrs enabled? true
2022-11-16 14:41:50,572 INFO  [main] namenode.NameNode (FSDirectory.java:<init>(406)) - Caching file names occurring more than 10 times
2022-11-16 14:41:50,578 INFO  [main] snapshot.SnapshotManager (SnapshotManager.java:<init>(124)) - Loaded config captureOpenFiles: false, skipCaptureAccessTimeOnlyChange: false, snapshotDiffAllowSnapRootDescendant: true, maxSnapshotLimit: 65536
2022-11-16 14:41:50,580 INFO  [main] snapshot.SnapshotManager (DirectoryDiffListFactory.java:init(43)) - SkipList is disabled
2022-11-16 14:41:50,586 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map cachedBlocks
2022-11-16 14:41:50,586 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2022-11-16 14:41:50,586 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 0.25% max memory 1.8 GB = 4.6 MB
2022-11-16 14:41:50,586 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^19 = 524288 entries
2022-11-16 14:41:50,594 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(75)) - NNTop conf: dfs.namenode.top.window.num.buckets = 10
2022-11-16 14:41:50,594 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(77)) - NNTop conf: dfs.namenode.top.num.users = 10
2022-11-16 14:41:50,594 INFO  [main] metrics.TopMetrics (TopMetrics.java:logConf(79)) - NNTop conf: dfs.namenode.top.windows.minutes = 1,5,25
2022-11-16 14:41:50,603 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:initRetryCache(1084)) - Retry cache on namenode is enabled
2022-11-16 14:41:50,604 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:initRetryCache(1092)) - Retry cache will use 0.03 of total heap and retry cache entry expiry time is 600000 millis
2022-11-16 14:41:50,606 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(395)) - Computing capacity for map NameNodeRetryCache
2022-11-16 14:41:50,606 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(396)) - VM type       = 64-bit
2022-11-16 14:41:50,606 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(397)) - 0.029999999329447746% max memory 1.8 GB = 559.3 KB
2022-11-16 14:41:50,606 INFO  [main] util.GSet (LightWeightGSet.java:computeCapacity(402)) - capacity      = 2^16 = 65536 entries
2022-11-16 14:41:55,691 INFO  [main] namenode.FSImage (FSImage.java:format(186)) - Allocated new BlockPoolId: BP-409822342-192.168.0.22-1668631315644
2022-11-16 14:41:55,716 INFO  [main] common.Storage (NNStorage.java:format(595)) - Storage directory /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-1 has been successfully formatted.
2022-11-16 14:41:55,718 INFO  [main] common.Storage (NNStorage.java:format(595)) - Storage directory /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-2 has been successfully formatted.
2022-11-16 14:41:55,845 INFO  [FSImageSaver for /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-2 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(732)) - Saving image file /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-2/current/fsimage.ckpt_0000000000000000000 using no compression
2022-11-16 14:41:55,845 INFO  [FSImageSaver for /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-1 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(732)) - Saving image file /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-1/current/fsimage.ckpt_0000000000000000000 using no compression
2022-11-16 14:41:56,097 INFO  [FSImageSaver for /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-2 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(736)) - Image file /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-2/current/fsimage.ckpt_0000000000000000000 of size 403 bytes saved in 0 seconds .
2022-11-16 14:41:56,097 INFO  [FSImageSaver for /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-1 of type IMAGE_AND_EDITS] namenode.FSImageFormatProtobuf (FSImageFormatProtobuf.java:save(736)) - Image file /Users/ctopinka/oss/MiniOozieExample/target/test/data/dfs/name-0-1/current/fsimage.ckpt_0000000000000000000 of size 403 bytes saved in 0 seconds .
2022-11-16 14:41:56,165 INFO  [main] namenode.NNStorageRetentionManager (NNStorageRetentionManager.java:getImageTxIdToRetain(203)) - Going to retain 1 images with txid >= 0
2022-11-16 14:41:56,188 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:stopActiveServices(1431)) - Stopping services started for active state
2022-11-16 14:41:56,188 INFO  [main] namenode.FSNamesystem (FSNamesystem.java:stopStandbyServices(1535)) - Stopping services started for standby state
2022-11-16 14:41:56,192 INFO  [main] namenode.NameNode (NameNode.java:createNameNode(1709)) - createNameNode []
2022-11-16 14:41:56,257 WARN  [main] impl.MetricsConfig (MetricsConfig.java:loadFirst(136)) - Cannot locate configuration: tried hadoop-metrics2-namenode.properties,hadoop-metrics2.properties
2022-11-16 14:41:56,357 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:startTimer(378)) - Scheduled Metric snapshot period at 10 second(s).
2022-11-16 14:41:56,358 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:start(191)) - NameNode metrics system started
2022-11-16 14:41:56,375 INFO  [main] namenode.NameNodeUtils (NameNodeUtils.java:getClientNamenodeAddress(79)) - fs.defaultFS is hdfs://127.0.0.1:0
2022-11-16 14:41:56,455 INFO  [org.apache.hadoop.util.JvmPauseMonitor$Monitor@1b765a2c] util.JvmPauseMonitor (JvmPauseMonitor.java:run(188)) - Starting JVM pause monitor
2022-11-16 14:41:56,468 INFO  [main] hdfs.MiniDFSCluster (MiniDFSCluster.java:shutdown(2109)) - Shutting down the Mini HDFS Cluster

java.lang.IncompatibleClassChangeError: Implementing class

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:953)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:765)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:1020)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:995)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1769)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1374)
	at org.apache.hadoop.hdfs.MiniDFSCluster.configureNameService(MiniDFSCluster.java:1143)
	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1016)
	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:948)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:864)
	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:733)
	at org.apache.oozie.test.XTestCase.setUpEmbeddedHadoop(XTestCase.java:999)
	at org.apache.oozie.test.XTestCase.setUp(XTestCase.java:452)
	at org.apache.oozie.test.XTestCase.setUp(XTestCase.java:310)
	at org.apache.oozie.test.XFsTestCase.setUp(XFsTestCase.java:70)
	at org.apache.oozie.test.MiniOozieTestCase.setUp(MiniOozieTestCase.java:63)
	at com.github.rkanter.minioozieexample.TestRunWorkflow.setUp(TestRunWorkflow.java:16)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code 255


```

**Comment by christopinka** [comment]
also blows up with java 8 with clone of project

```
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


```

or when I run the test from the ide

```

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Could not determine project root directory

```
